server:
  port: 8084
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: NOTIF_USER
    password: NOTIF_PASSWORD
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
  mail:
    host: localhost
    port: 1025
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
springdoc:
  api-docs:
    enabled: true
