server:
  port: 8083
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: PAYMENT_USER
    password: PAYMENT_PASSWORD
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
springdoc:
  api-docs:
    enabled: true
